import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.gradle.api.provider.Provider
import org.gradle.jvm.toolchain.JavaLanguageVersion
import org.gradle.jvm.toolchain.JvmVendorSpec

plugins {
    // Kotlin/JVM + the shared JVM toolchain (from ProjectConfig). This convention no
    // longer applies Gradle's `application` plugin — Compose Desktop supplies `run`.
    id("deferno.jvm.application")
    // Compose Desktop (ADR-0003: desktop View = Compose Desktop): the runtime + the
    // `compose.desktop.application` packaging/run DSL.
    alias(libs.plugins.compose.multiplatform)
    // The Compose *compiler* plugin (pinned to the Kotlin version via the catalog).
    alias(libs.plugins.kotlin.compose)
}

// The desktop app runs on, and ships with, the **JetBrains Runtime** — the JDK Compose Desktop is
// built for. Stock OpenJDK on Linux renders worse and ends up with dated, AWT-drawn window chrome,
// while JBR integrates with the window manager (native KDE Breeze decorations, etc.) and the OS
// dark/light theme. `compose.desktop.application.javaHome` (set below) is what Compose uses for BOTH
// the dev `run` task and the jpackage/jlink packaging — so the bundled distribution runtime is JBR
// too. Resolved (and auto-provisioned) via the Foojay resolver at the project's Java 17 level
// (ProjectConfig.JVM_TOOLCHAIN); compile/test stay on the shared toolchain (the runtime JVM only
// matters for the GUI). jbrsdk ships jmods, so jlink/jpackage can build the native distributions.
val jetbrainsRuntimeHome: String = javaToolchains.launcherFor {
    languageVersion.set(JavaLanguageVersion.of(17))
    vendor.set(JvmVendorSpec.JETBRAINS)
}.get().metadata.installationPath.asFile.absolutePath

// --- Dev-PAT codegen (the desktop analog of Android's BuildConfig, #68/#83, ADR-0012) ----------------
// Surface dev-account PATs from the gitignored root local.properties into a generated Kotlin constant
// the app reads at startup, so a developer can open real staging data without committing a token. It
// reads the SAME keys Android does (deferno.dev.accounts / deferno.staging.apiToken) and the shared
// DevAccounts.from(...) parses them — blank when unset, so nothing is seeded. Read via
// providers.fileContents to stay configuration-cache compatible and re-run when the token changes
// (mirrors the deferno.kmp Test wiring). There is no debug/release split on desktop: a distributed
// build simply has no keys configured on the build machine, so no PAT ships.
val localProperties = providers.fileContents(
    rootProject.layout.projectDirectory.file("local.properties"),
).asText.orElse("")

fun devProperty(key: String): Provider<String> =
    localProperties.map { text ->
        text.lineSequence()
            .firstOrNull { it.startsWith("$key=") }
            ?.substringAfter('=')?.trim().orEmpty()
    }

val generatedDevConfigDir = layout.buildDirectory.dir("generated/devconfig/kotlin")

val generateDesktopDevConfig = tasks.register("generateDesktopDevConfig") {
    val devAccounts = devProperty("deferno.dev.accounts")
    val stagingToken = devProperty("deferno.staging.apiToken")
    val outDir = generatedDevConfigDir
    inputs.property("devAccounts", devAccounts)
    inputs.property("stagingToken", stagingToken)
    outputs.dir(outDir)
    doLast {
        // Render a Kotlin string literal (escape backslash + quote; PATs are single-line base64url/JWT).
        fun literal(value: String): String =
            "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\""
        val pkgDir = outDir.get().asFile.resolve("com/circuitstitch/deferno/desktop")
        pkgDir.mkdirs()
        pkgDir.resolve("DesktopDevConfig.kt").writeText(
            """
            |package com.circuitstitch.deferno.desktop
            |
            |/**
            | * Dev-account PATs surfaced from the gitignored `local.properties` at build time (#68/#83,
            | * ADR-0012) — the desktop analog of Android's `BuildConfig`. Both fields are blank when the
            | * keys are unset, so the shared [com.circuitstitch.deferno.DevAccounts].from(...) seeds
            | * nothing. GENERATED by the `generateDesktopDevConfig` Gradle task — do not edit.
            | */
            |internal object DesktopDevConfig {
            |    const val DEV_ACCOUNTS: String = ${literal(devAccounts.get())}
            |    const val DEV_STAGING_TOKEN: String = ${literal(stagingToken.get())}
            |}
            |
            """.trimMargin(),
        )
    }
}

// Add the generated source to the main Kotlin source set; passing the TaskProvider makes the Kotlin
// compile task depend on the generator automatically.
kotlin {
    sourceSets.named("main") {
        kotlin.srcDir(generateDesktopDevConfig)
    }
}

// Compose Desktop's own application DSL (replaces Gradle's built-in `application`):
// it owns `mainClass` and the `run` task and wires Skiko onto the runtime classpath.
compose.desktop.application {
    mainClass = "com.circuitstitch.deferno.desktop.MainKt"
    // Run + package on the JetBrains Runtime (see note above); bundles JBR into the distribution.
    javaHome = jetbrainsRuntimeHome
    nativeDistributions {
        // Each installer format only builds on its host OS; configuring all three is
        // harmless cross-platform (Deb is the one this Linux box can actually produce).
        targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
        packageName = "Deferno"
        packageVersion = "1.0.0"
    }
}

dependencies {
    // Compose Desktop runtime for the host OS (bundles Skiko) + Material 3 + the core Material icon
    // set the nav rail/drawer uses (the androidx adaptive nav-suite the Android shell uses is an
    // Android-only artifact, so desktop builds its own native rail/drawer here).
    implementation(compose.desktop.currentOs)
    implementation(compose.material3)
    // Just the core Material icon set (the glyphs the nav rail/drawer uses) — not the ≈37 MB
    // `materialIconsExtended` set, which the bundled desktop distribution would otherwise ship.
    implementation(libs.compose.material.icons.core)

    // The shared, Compose-free app Shell (ADR-0017): the desktop renders these components
    // (RootComponent: Auth ↔ Main; the Main shell's Destination graph; AccountSession +
    // AccountComponentSession; DevAccounts) with its own native Views (rail/drawer + in-app menu bar).
    // It replaces the retired desktop `shell/*.kt` component duplicates. app:shell api-exposes
    // Decompose + coroutines + datetime, but its core/feature deps are `implementation`, so the ones
    // the desktop host references directly are named below.
    implementation(project(":app:shell"))

    // The compile-time DI graph (#68, ADR-0014): the desktop builds the process-global AppComponent and
    // a per-Account AccountComponent off the JVM graph (createAppComponent / createAccountComponent),
    // exactly as DefernoApplication + MainActivity do on Android (ADR-0017).
    implementation(project(":core:di"))
    // PlatformContext(databasesDir) — the per-Account file-backed SQLite location handed to the graph.
    implementation(project(":core:scopes"))
    // DefernoEnvironment selects the backend (Staging) at startup and derives the web-app origin for
    // the Settings deep-links (data export/import, feedback, console URL).
    implementation(project(":core:network"))
    // AccountManager (the RootComponent keys off its activeAccount) + AuthRepository (the Profile
    // Destination's /auth/me), both read off the AppComponent and threaded into the shared root.
    implementation(project(":core:data"))
    // CreateItem.Payload / CommandResult appear in the shared AccountSession API surface the desktop
    // adapts (AccountComponentSession), so they must be resolvable on the desktop compile classpath.
    implementation(project(":core:domain"))
    // Account / AccountId for the in-app Account switcher; ThemeFamily for live theming.
    implementation(project(":core:model"))
    // DefernoTheme + palette for the Compose host (live-themed off the shared root, ADR-0017).
    implementation(project(":core:designsystem"))

    // The feature slices the shared Main shell composes. Plan + Tasks render their existing desktop
    // Views (the :ui submodules' jvmMain); Profile + Settings render a placeholder on desktop for now
    // (their jvmMain Views are later slices, #84/#85), but their *logic* modules are on the compile
    // classpath because the Main shell View pattern-matches the Profile/Settings DestinationChild.
    implementation(project(":feature:plan"))
    implementation(project(":feature:plan:ui"))
    implementation(project(":feature:tasks"))
    implementation(project(":feature:tasks:ui"))
    implementation(project(":feature:profile"))
    implementation(project(":feature:settings"))
    // The Settings Destination's desktop View (#85): the shared Main shell renders it in the content
    // area (its jvmMain SettingsDesktopScreen, the desktop counterpart of the Android settings screen).
    implementation(project(":feature:settings:ui"))

    // Decompose: the shell/Destination component tree + `subscribeAsState()` Compose bindings, and
    // `LifecycleController`, which drives Essenty's LifecycleRegistry off the desktop window state
    // (the desktop counterpart of Android's `retainedComponent`).
    implementation(libs.decompose)
    implementation(libs.decompose.extensions.compose)
    // The shared root collects AccountManager.activeAccount to drive Decompose navigation, which must
    // run on the UI (AWT EDT) thread — Dispatchers.Swing supplies that dispatcher. The shell observes
    // Flows; the host computes today's date.
    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.kotlinx.coroutines.swing)
    implementation(libs.kotlinx.datetime)

    // The pure desktop-View breakpoint test (DesktopNavKindTest). The shared shell *components* are
    // tested in app/shell's commonTest (ADR-0017), so the desktop no longer duplicates those tests.
    testImplementation(libs.junit)
}
