plugins {
    // SDK levels + JVM toolchain come from the deferno.android.application convention
    // (shared with the library modules via ProjectConfig). The Compose compiler plugin
    // is applied explicitly; AGP 9 compiles Kotlin itself, so no kotlin-android plugin.
    id("deferno.android.application")
    alias(libs.plugins.kotlin.compose)
    // Screenshot tests (#27): Roborazzi renders the feature Compose Views through Robolectric on the
    // JVM and adds the record/verify tasks. This is the well-trodden Roborazzi home (a
    // com.android.application unit-test source set), chosen over the feature modules' KMP-android host
    // test to reuse the Compose-BOM test infra and avoid the KMP/androidx test-artifact friction.
    alias(libs.plugins.roborazzi)
    // Startup Baseline Profile (cold-start AOT): the consumer side. This plugin merges the profile
    // generated by the `:baselineprofile` module into the release APK's `assets/dexopt/baseline.prof`,
    // so ProfileInstaller AOT-compiles the hot startup path on install instead of verifying +
    // JIT-compiling it at runtime on every launch (the `run-from-apk` default). It also derives the
    // `nonMinifiedRelease`/`benchmarkRelease` variants the generator builds against.
    alias(libs.plugins.androidx.baselineprofile)
}

// Surface dev-account PATs from the gitignored root local.properties into the *debug* BuildConfig
// (#68, ADR-0012): a developer pastes one or more PATs and the app seeds those Accounts on first run,
// so it shows real staging data without committing a token. Absent-safe (blank when unset) and
// debug-only — a release build's fields are empty, so no PAT can ship. Read via providers.fileContents
// to stay configuration-cache compatible (same pattern as the deferno.kmp Test wiring).
//
// Format (local.properties):
//   deferno.dev.accounts=work:Work:<PAT1>;personal:Personal:<PAT2>   (id:label:token, ';'-separated)
// Back-compat: a lone deferno.staging.apiToken (already used by the #20 integration test) seeds one
// "Dev (staging)" account, so an existing setup needs no change. See DevAccounts for the parser.
val localProperties = providers.fileContents(
    rootProject.layout.projectDirectory.file("local.properties"),
).asText.orElse("")

fun localProperty(key: String): String =
    localProperties.get().lineSequence()
        .firstOrNull { it.startsWith("$key=") }
        ?.substringAfter('=')?.trim().orEmpty()

// Render a Java string literal for buildConfigField (escape backslash + quote; PATs are single-line
// base64url/JWT, so no newline handling is needed).
fun stringLiteral(value: String): String =
    "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\""

android {
    namespace = "com.circuitstitch.deferno"

    // The on-device whisper model ships as a Play Asset Delivery INSTALL-TIME pack (#92, ADR-0019):
    // present from first launch but OFF the base-APK size budget (not bundled in the binary). The pack
    // is populated by :speech-model-pack:downloadWhisperModel (see the preBuild hook below).
    assetPacks += listOf(":speech-model-pack")

    defaultConfig {
        applicationId = "com.circuitstitch.deferno"
        // versionName / versionCode derive from ProjectConfig.APP_VERSION via the
        // deferno.android.application convention (the single version source of truth, ADR-0021/#101).

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            // Dev PAT login placeholder (#68): seed Accounts from local.properties on debug builds.
            buildConfigField("String", "DEV_ACCOUNTS", stringLiteral(localProperty("deferno.dev.accounts")))
            buildConfigField("String", "DEV_STAGING_TOKEN", stringLiteral(localProperty("deferno.staging.apiToken")))
        }
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
            // No PAT ever ships in a release build (#68 phase 5 verifies this).
            buildConfigField("String", "DEV_ACCOUNTS", "\"\"")
            buildConfigField("String", "DEV_STAGING_TOKEN", "\"\"")
        }
    }

    // The androidx.baselineprofile plugin derives `nonMinifiedRelease` (profile generation) and
    // `benchmarkRelease` (measurement) from `release`. This project has no release signing config yet
    // (no keystore, pre-release), so those generated variants would be unsigned and fail to install on
    // device during `generateBaselineProfile`. Sign ONLY those two with the always-present debug key —
    // the real `release` variant is left untouched, so it still demands a real key once one exists.
    // `configureEach` (not `getByName`) so it also catches the build types the plugin adds.
    buildTypes.configureEach {
        if (name == "nonMinifiedRelease" || name == "benchmarkRelease") {
            signingConfig = signingConfigs.getByName("debug")
        }
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    testOptions {
        // Robolectric/Roborazzi render against the merged Android resources (incl. the design
        // system's Compose resources/fonts) on the JVM-fast unit-test path (#27, ADR-0006).
        unitTests {
            isIncludeAndroidResources = true
        }
    }
}

// Baseline Profile: scaffolding is KEPT but the profile is switched OFF. The `:baselineprofile`
// generator + plugin wiring stay so this can be turned on later as physical-device automation — a fast
// x86 emulator can't demonstrate the AOT win (measured: release cold start ~840 ms with or without
// AOT), so the profile must be generated + measured on real ARM hardware. No emulator-generated profile
// is committed (it reflected the no-account x86 launch path). To turn ON: uncomment the
// `baselineProfile(project(":baselineprofile"))` dependency below and run
// `:app:androidApp:generateBaselineProfile` against a connected physical device.
baselineProfile {
    // With the producer dependency commented out (off), the plugin would otherwise warn on every build
    // that no baseline profile is wired — silence it so day-to-day builds stay clean while off.
    warnings {
        variantHasNoBaselineProfileDependency = false
    }
}

// Fetch the whisper model into the install-time asset pack before the app is built (#92, ADR-0019).
// preBuild is the earliest app task, so the pack is populated before asset packaging reads it. The
// download task no-ops when the model is already present and only warns (never fails) when offline.
tasks.matching { it.name == "preBuild" }.configureEach {
    dependsOn(":speech-model-pack:downloadWhisperModel")
}

dependencies {
    // The shared, Compose-free app Shell (ADR-0017): the shell *components* (RootComponent, Main shell
    // + Destination graph, AccountSession, New, Auth) now live in :app:shell; this module owns only the
    // Android-native *Views* that render them (RootShell, MainShell's NavigationSuiteScaffold, NewScreen,
    // in src/main/.../shell) — the phone nav surface, not a desktop/iOS layout stretched (ADR-0007).
    implementation(project(":app:shell"))
    // The feature slices: the logic modules supply the component types the Views reference directly
    // (PlanComponent, TasksComponent, …); the `:ui` submodules supply the Android-native screens.
    // core:designsystem provides DefernoTheme for the Compose host.
    implementation(project(":feature:tasks"))
    implementation(project(":feature:tasks:ui"))
    implementation(project(":feature:plan"))
    implementation(project(":feature:plan:ui"))
    implementation(project(":feature:calendar"))
    implementation(project(":feature:calendar:ui"))
    implementation(project(":feature:auth"))
    implementation(project(":feature:auth:ui"))
    implementation(project(":feature:profile"))
    implementation(project(":feature:profile:ui"))
    implementation(project(":feature:settings"))
    implementation(project(":feature:settings:ui"))
    implementation(project(":core:model"))
    implementation(project(":core:data"))
    // DefernoEnvironment selects the backend at startup (DefernoApplication) and derives the web-app
    // origin for the Settings deep-links (MainActivity.webAppUrl, #72).
    implementation(project(":core:network"))
    // The compile-time DI graph (#68, ADR-0014): the app builds AppComponent at startup and an
    // AccountComponent per Active Account (createAppComponent / createAccountComponent).
    implementation(project(":core:di"))
    implementation(project(":core:designsystem"))
    // Decompose: `retainedComponent { }` builds the demo root so it survives configuration changes
    // (rotation) + back-press routing; `subscribeAsState()` observes the tab/slots from Compose.
    implementation(libs.decompose)
    implementation(libs.decompose.extensions.compose)
    // The demo repositories expose Kotlin Flows; the Plan root computes today's date.
    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.kotlinx.datetime)

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)
    // Applies the bundled startup Baseline Profile (generated by :baselineprofile) at install time so
    // the hot path is AOT-compiled, not verified+JIT'd at runtime. Present transitively via Compose;
    // declared explicitly so the consumer side of the baseline profile isn't merely incidental.
    implementation(libs.androidx.profileinstaller)
    // Links this app (consumer) to the :baselineprofile generator (producer): `generateBaselineProfile`
    // pulls the freshly-generated profile from there into src/release/generated and the release build
    // merges it into the APK. Currently OFF (see the `baselineProfile {}` block above) so no profile is
    // generated or bundled and the emulator can't accidentally regenerate a non-representative one.
    // Uncomment to enable on a connected physical device:
    // baselineProfile(project(":baselineprofile"))

    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.ui)
    implementation(libs.androidx.ui.graphics)
    implementation(libs.androidx.ui.tooling.preview)
    implementation(libs.androidx.material3)
    // The navigation shell (#55): NavigationSuiteScaffold + the window-size-class metric it adapts to.
    implementation(libs.androidx.material3.adaptive.navigation.suite)
    implementation(libs.androidx.material3.adaptive)
    implementation(libs.androidx.material.icons.core)

    // JVM-fast unit + screenshot tests for the Views (#27): Robolectric runs the Compose UI tests +
    // Roborazzi screenshots without a device, rendering the Views through their public
    // `*Screen(component)` entry points driven by tiny fakes (see src/test). The feature/UI + data
    // modules they touch are already on the main classpath above (testImplementation extends it).
    // The shell *components* moved to :app:shell (ADR-0017), but the Android-native View interaction
    // tests still drive DefaultMainShellComponent directly — the New-overlay test supplies a `create`
    // seam typed in core:domain (CreateItem / CommandResult), so name it for the test classpath only.
    testImplementation(project(":core:domain"))
    testImplementation(libs.junit)
    testImplementation(libs.robolectric)
    testImplementation(libs.roborazzi)
    testImplementation(libs.roborazzi.compose)
    testImplementation(libs.roborazzi.junit.rule)
    testImplementation(platform(libs.androidx.compose.bom))
    testImplementation(libs.androidx.ui.test.junit4)
    testImplementation(libs.androidx.ui.test.manifest)

    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.ui.test.junit4)

    debugImplementation(libs.androidx.ui.tooling)
    debugImplementation(libs.androidx.ui.test.manifest)
}
